/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HotelManagement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
//import net.proteanit.sql.DbUtils;

/**
 *
 * @author Chaker
 */
public class Chambres extends javax.swing.JFrame {

    /**
     * Creates new form Chambres
     */
    public Chambres() {
        initComponents();
        Connection();
        remplissage();
    }
    
    Connection conn ;
    Statement st ;
    PreparedStatement set ;
    ResultSet rs ;
    public void Connection ()
    {
        
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/hotel", "root", "") ;
                System.out.print("connection avec succées ");
              
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Reservation.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
            Logger.getLogger(Reservation.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }
    
    public ArrayList<Chambrecontenu> contenu(){
        ArrayList<Chambrecontenu> con=null ;
     con=new ArrayList<Chambrecontenu>();
     try{
     String sql="SELECT * FROM `chambres`;";
     st=conn.createStatement();
     rs=st.executeQuery(sql);
     Chambrecontenu chambre;
     while(rs.next()){
       chambre = new Chambrecontenu(rs.getInt(1),rs.getInt(2),rs.getString("etage"),rs.getInt(4));
     con.add(chambre);
     }
     }catch(Exception ex){
     Logger.getLogger(Reservation.class.getName()).log(Level.SEVERE, null, ex);
     }
        
        return con ;
    }
    public void remplissage(){
     ArrayList<Chambrecontenu> con= contenu();
     DefaultTableModel mod=(DefaultTableModel)table.getModel();
     mod.setRowCount(0);
     Object[] rw=new Object[4];
     for(int i = 0; i < con.size(); i++){
         rw[0]=con.get(i).getChambre_id();
         rw[1]=con.get(i).getNumero();
         rw[2]=con.get(i).getEtage();
         rw[3]=con.get(i).getNb_place();
         mod.addRow(rw);
     }
 }
    
    public void affichage (int ind){
     
      txtchambreid.setText(Integer.toString(contenu().get(ind).getChambre_id()));
      txtnum.setText(Integer.toString(contenu().get(ind).getNumero()));
      txtetage.setText(contenu().get(ind).getEtage());
      txtplace.setText(Integer.toString(contenu().get(ind).getNb_place()));
     
 }  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtnum = new javax.swing.JTextField();
        txtchambreid = new javax.swing.JTextField();
        txtetage = new javax.swing.JTextField();
        txtplace = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        jButton1.setFont(new java.awt.Font("DejaVu Sans Mono", 1, 11)); // NOI18N
        jButton1.setText("Chambres Réservé");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("DejaVu Sans Mono", 1, 11)); // NOI18N
        jButton2.setText("Chabmres Libre");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "chambre_id", "numero", "etage", "nb_place"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Short.class, java.lang.String.class, java.lang.Short.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jButton3.setFont(new java.awt.Font("DejaVu Sans Mono", 1, 11)); // NOI18N
        jButton3.setText("Actualiser");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("DejaVu Sans Mono", 1, 11)); // NOI18N
        jButton4.setText("Ajouer");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("DejaVu Sans Mono", 1, 11)); // NOI18N
        jButton5.setText("Modifier");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("DejaVu Sans Mono", 1, 11)); // NOI18N
        jButton6.setText("Supprimer");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("DejaVu Sans Mono", 1, 11)); // NOI18N
        jLabel3.setText("Chambre ID :");

        jLabel4.setFont(new java.awt.Font("DejaVu Sans Mono", 1, 11)); // NOI18N
        jLabel4.setText("Numero Chambre :");

        jLabel5.setFont(new java.awt.Font("DejaVu Sans Mono", 1, 11)); // NOI18N
        jLabel5.setText("Etage :");

        jLabel6.setFont(new java.awt.Font("DejaVu Sans Mono", 1, 11)); // NOI18N
        jLabel6.setText("NB Place :");

        txtnum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnumKeyTyped(evt);
            }
        });

        txtchambreid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtchambreidKeyTyped(evt);
            }
        });

        txtplace.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtplaceKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtnum)
                            .addComponent(txtchambreid)
                            .addComponent(txtetage)
                            .addComponent(txtplace, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtchambreid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtetage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtplace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jButton5)
                            .addComponent(jButton6))))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 74, 760, 390));

        jPanel2.setBackground(java.awt.Color.darkGray);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("CHAMBRES");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HotelManagement/eeeee.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(223, 223, 223)
                .addComponent(jLabel1)
                .addContainerGap(283, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 42, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       ChambresLibre chl = new ChambresLibre();
        chl.setVisible(true);
        chl.pack();
        chl.setLocationRelativeTo(null);
        chl.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
ChambresReservé ch = new ChambresReservé();
        ch.setVisible(true);
        ch.pack();
        ch.setLocationRelativeTo(null);
        ch.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        txtchambreid.setText("");
        txtnum.setText("");
        txtetage.setText("");
        txtplace.setText("");
        remplissage();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        Welcome wel = new Welcome();
        wel.setVisible(true);
        wel.pack();
        wel.setLocationRelativeTo(null);
        wel.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String etage = txtetage.getText();
        if(etage.trim().equals("")
                ){
            JOptionPane.showMessageDialog(null, "Remplir tous les champs");
        } else if(txtchambreid.getText()!=null || txtetage.getText()!=null || 
                 txtnum!=null || txtplace!=null ) {
            
            try {
                String sql="SELECT chambre_id FROM `chambres` where chambre_id =?;";
                set=conn.prepareStatement(sql);
                set.setInt(1, Integer.parseInt(txtchambreid.getText()));
                rs= set.executeQuery();
                if(rs.next()){
                        JOptionPane.showMessageDialog(null, "Chambre ID déja existe");
                    }else{
                      try{
                          String sql1="SELECT numero FROM `chambres` where numero =?;";
                set=conn.prepareStatement(sql1);
                set.setInt(1, Integer.parseInt(txtnum.getText()));
                rs= set.executeQuery();
                if(rs.next()){
                        JOptionPane.showMessageDialog(null, "Numero Chambre déja existe");
                    }else{
                    
                    
                    try{
                    String sql2 = "INSERT INTO `chambres`(chambre_id, numero, etage, nb_place) VALUES (?, ?, ?, ?);";
                    set=conn.prepareStatement(sql2);
                    set.setInt(1, Integer.parseInt(txtchambreid.getText()));
                    set.setInt(2, Integer.parseInt(txtnum.getText()));
                    set.setString(3, etage);
                    set.setInt(4, Integer.parseInt(txtplace.getText()));
                    int res=set.executeUpdate();
                    remplissage();
                    if(res<=1){
                    JOptionPane.showMessageDialog(null, "Succéess" );
                }else{
                    JOptionPane.showMessageDialog(null, "Erreur");
                }
                    } catch (SQLException ex) {
                Logger.getLogger(Chambres.class.getName()).log(Level.SEVERE, null, ex);
            }
                }
                     }catch(Exception ex){
                             Logger.getLogger(Chambres.class.getName()).log(Level.SEVERE, null, ex);
                         }
                }
            } catch (SQLException ex) {
                Logger.getLogger(Chambres.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         String etage = txtetage.getText();
        if(etage.trim().equals("")
                ){
            JOptionPane.showMessageDialog(null, "Remplir tous les champs");
        } else if(txtchambreid.getText()!=null || txtetage.getText()!=null || 
                 txtnum!=null || txtplace!=null ) {
            try{
                    String sql2 = "UPDATE `chambres` SET numero=?, etage=?, nb_place=? WHERE chambre_id=? ;";
                    set=conn.prepareStatement(sql2);
                    
                    set.setInt(1, Integer.parseInt(txtnum.getText()));
                    set.setString(2, etage);
                    set.setInt(3, Integer.parseInt(txtplace.getText()));
                    set.setInt(4, Integer.parseInt(txtchambreid.getText()));
                    int res=set.executeUpdate();
                    remplissage();
                    if(res<=1){
                    JOptionPane.showMessageDialog(null, "Succéess" );
                }else{
                    JOptionPane.showMessageDialog(null, "Erreur");
                }
                    } catch (SQLException ex) {
                Logger.getLogger(Chambres.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         if(txtchambreid.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Entrer Chambre Id pour effacer la Chambre");
        }else{ try {
                String del = "DELETE FROM `chambres` WHERE chambre_id=?;";
                set = conn.prepareStatement(del);
                set.setInt(1, Integer.parseInt(txtchambreid.getText()));
                int res =set.executeUpdate();
                remplissage();
                if(res>=1){
                    JOptionPane.showMessageDialog(null, "Chambre supprimé", "Suppression", 2 );
                }else{
                    JOptionPane.showMessageDialog(null, "Chambre n'est pas existant");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Cette chambre est réservé tu ne peut pas l'éffacer");
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txtchambreidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtchambreidKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_txtchambreidKeyTyped

    private void txtnumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnumKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_txtnumKeyTyped

    private void txtplaceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtplaceKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_txtplaceKeyTyped

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        int i= table.getSelectedRow();
             affichage(i);
             TableModel mod = table.getModel();
        remplissage();
    }//GEN-LAST:event_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chambres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chambres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chambres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chambres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Chambres().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtchambreid;
    private javax.swing.JTextField txtetage;
    private javax.swing.JTextField txtnum;
    private javax.swing.JTextField txtplace;
    // End of variables declaration//GEN-END:variables
}
